name: Check
on: [ pull_request, push ]
jobs:
  check:
    runs-on: ubuntu-latest
    # push: always run.
    # pull_request: run only when the PR is submitted from a forked repository, not within this repository.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Set up OpenJDK 8
      uses: actions/setup-java@v3
      with:
        java-version: 8
        distribution: "temurin"
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 'jruby-9.4.2.0' # Not needed with a .ruby-version file
        bundler-cache: true
    - name: show ruby version
      run: ruby -v
    - name: bundle install
      run: bundle install
    - name: install embulk
#      run: "curl --create-dirs -o ~/.embulk/bin/embulk https://github.com/embulk/embulk/releases/download/v0.10.49/embulk-0.10.49.jar"
      run: "curl --create-dirs -o embulk.jar https://github.com/embulk/embulk/releases/download/v0.10.49/embulk-0.10.49.jar"
#    - name: chmod embulk
#      run: "chmod 755 ~/.embulk/bin/embulk"
    - name: rake test
      run: 'RUBY_OPTS="-r ./embulk.jar" rake test'


#    - name: Check
#      run: ./gradlew --stacktrace check
